site_name: Guia de Testes de Acessibilidade Digital

theme:
  name: material
  features:
    # - navigation.tabs
    - toc.integrate  # isso ativa o índice lateral por seção
    - skip-to-content
    - content.code.copy  # melhora usabilidade
    - navigation.instant
    - search.highlight
    - skip-to-content    
    - navigation.footer
    
extra_css:
  - styles/extra.css

nav:
  - Início: index.md
  - Fundamentos de Acessibilidade Digital: fundamentos.md
  - Abordagem Colaborativa: abordagem_colaborativa.md
  - Sugestão de Ferramentas para Testes de Acessibilidade: ferramentas.md
  - Diferenciação Por Tipo De Falha Em Testes De Acessibilidade: diferenciar_acessibilidade.md  
  - Classificação por Nível de Gravidade dos Defeitos de Acessibilidade: classificacao_defeitos.md
  - Verificações de Acessibilidade por Perfil de Usuário: verificacoes_por_deficiencia.md
  - Erros Recorrentes em Testes de Acessibilidade: erros_recorrentes.md
  - Definition of Ready: dor.md
  - Roteiros de Teste: roteiros.md  
  - Boas Práticas e Considerações Finais: boas_praticas.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.snippets
  - attr_list

extra_javascript:
  - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js